objs = [
        {
        "cadastradoPor": "Dominic Toretto",
        "contato": "dominict@fast.com",
        "uf": "DF",
        "cidade": "Brasilia",
        "descricao": "pouco uso",
        "marca": "Alfa Romeo",
        "modelo": "145 Elegant 2.0 16V",
        "cor": "preto",
        "ano": 1998,
        "combustivel": "gasolina",
        "transmissao": "manual",
        "preco": 12759,
        "urlFotoPrincipal": "https://cloud.leparking.fr/2021/05/02/09/04/alfa-romeo-145-145-elegant-2-0-16v-preto_8094872339.jpg",
        "dataCadastro": Date.now(),
        "dataAtualizacao": Date.now()
    },
    {
        "cadastradoPor": "Dominic Toretto",
        "contato": "dominict@fast.com",
        "uf": "DF",
        "cidade": "Brasilia",
        "descricao": "pouco uso",
        "marca": "Alfa Romeo",
        "modelo": "Spider 2.0\/3.0",
        "cor": "amerelo",
        "ano": 1993,
        "combustivel": "gasolina",
        "transmissao": "automática",
        "preco": 18666,
        "urlFotoPrincipal": "https://motos-motor.com.br/c/wp-content/uploads/precos-tabela-alfa-romeo-spider-20-30.jpg",
        "dataCadastro": Date.now(),
        "dataAtualizacao": Date.now()
    },
    {
        "cadastradoPor": "Brian O'Conner",
        "contato": "brian@fast.com",
        "uf": "RJ",
        "cidade": "Rio de Janeiro",
        "descricao": "10.000 km",
        "marca": "Toyota",
        "modelo": "Band. Jipe 4x4 Sport 3.7 Diesel",
        "cor": "verde",
        "ano": 1999,
        "combustivel": "diesel",
        "transmissao": "manual",
        "preco": 32000,
        "urlFotoPrincipal": "https://cloud.leparking.fr/2021/05/02/09/04/alfa-romeo-145-145-elegant-2-0-16v-preto_8094872339.jpg",
        "dataCadastro": Date.now(),
        "dataAtualizacao": Date.now()
    },
    {
        "cadastradoPor": "Brian O'Conner",
        "contato": "brian@fast.com",
        "uf": "RJ",
        "cidade": "Rio de Janeiro",
        "descricao": "10.000 km",
        "marca": "Toyota",
        "modelo": "Corolla GLi 1.8 Flex 16V  Aut.",
        "cor": "preto",
        "ano": 1999,
        "combustivel": "gasolina",
        "transmissao": "automático",
        "preco": 90990,
        "urlFotoPrincipal": "https://quatrorodas.abril.com.br/wp-content/uploads/2017/06/qr-695-corolla-imagem-web-rgb-02-e1498488845350.jpg",
        "dataCadastro": Date.now(),
        "dataAtualizacao": Date.now()
    },
    {
        "cadastradoPor": "Leticia Ortiz",
        "contato": "leticia@fast.com",
        "uf": "SP",
        "cidade": "Osasco",
        "descricao": "carro muito linfo",
        "marca": "LAMBORGHINI",
        "modelo": "HURACAN EVO Spyder LP 640-4",
        "cor": "branco",
        "ano": 2020 ,
        "combustivel": "gasolina",
        "transmissao": "automático",
        "preco": 90990,
        "urlFotoPrincipal": "https://www.bentleygoldcoast.com/galleria_images/8213/8213_p4_l.jpg",
        "dataCadastro": Date.now(),
        "dataAtualizacao": Date.now()
    },
    {
        "cadastradoPor": "Leticia Ortiz",
        "contato": "leticia@fast.com",
        "uf": "SP",
        "cidade": "Osasco",
        "descricao": "carro muito linfo",
        "marca": "LAMBORGHINI",
        "modelo": "AVENTADOR 770-4 SVJ ROADSTER V12",
        "cor": "azul",
        "ano": 2021 ,
        "combustivel": "gasolina",
        "transmissao": "automático",
        "preco": 90990,
        "urlFotoPrincipal": "https://image.webmotors.com.br/_fotos/AnuncioUsados/gigante/2021/202107/20210716/lamborghini-aventador-6.5-v12-gasolina-lp-7004-roadster-isr-wmimagem14365371744.jpg",
        "dataCadastro": Date.now(),
        "dataAtualizacao": Date.now()
    },
    {
        "cadastradoPor": "Leticia Ortiz",
        "contato": "leticia@fast.com",
        "uf": "SP",
        "cidade": "Osasco",
        "descricao": "carro muito linfo",
        "marca": "LAMBORGHINI",
        "modelo": "AVENTADOR 770-4 SVJ ROADSTER V12",
        "cor": "azul",
        "ano": 2021 ,
        "combustivel": "gasolina",
        "transmissao": "automático",
        "preco": 7062600,
        "urlFotoPrincipal": "https://image.webmotors.com.br/_fotos/AnuncioUsados/gigante/2021/202107/20210716/lamborghini-aventador-6.5-v12-gasolina-lp-7004-roadster-isr-wmimagem14365371744.jpg",
        "dataCadastro": Date.now(),
        "dataAtualizacao": Date.now()
    }
]

db.cars.drop()
db.createCollection("cars")
db.cars.insertMany(objs)
db.cars.count()
